### ISSUE TITLE
write a English version tutorial ?

### ISSUE THREAD

**Issue by jenenliu** [yaruopooner/msvc#1]
Hi, this is awesome, I've tried hard to find a great Emacs c++ dev environment under Windows, but can't find a good one, now maybe I think I've found it. The problem is I don't understand Japanese and I try to translate it but it is not so clear. Can you please write a English version , thanks.
BTW, does it support visual studio ultimate 2013? or just support professional version ?

**Comment by yaruopooner** [comment]
English manual was released today.
Probably all editions should be available.
